- hosts: allnodes
  remote_user: root
  tasks:
    - name: reset node
      shell: /root/k8s-installer/k8s-script/cluster/reset_k8s_master.sh
    - name: pull k8s images
      shell: /root/k8s-installer/k8s-script/cluster/pull_k8s_image.sh
      retries: 2
    - name: install k8s
      shell: /root/k8s-installer/k8s-script/osinit/installk8s.sh

